name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g npm@latest
      - run: npm install -g eslint
      - run: npm install -g @nestjs/cli
      - run: npm install
      - run: npm ci --prod
      - run: npx nest build
